version: '3'
services:
  ghost:
    image: ghost:3.13.4
    restart: always
    expose:
      - "2368"
    env_file:
      .env
    volumes:
      - /opt/ghost_content:/var/lib/ghost/content
      - ./emails:/var/lib/ghost/versions/3.13.4/core/server/services/members/emails

  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - /etc/letsencrypt/:/etc/letsencrypt/
